
swagger:
  ui-config:
    api-sorter: alpha
    json-editor: true
    display-request-duration: true
  title: 测试Swagger 文档API
  contact:
    name: 公众号：行百里er
    email: 19193127929@qq.com
    url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI1MDU1MjkxOQ==#wechat_redirect
  base-package: com.travler100.test.swaggerdemo.controller

server:
  port: 8011